FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://code-server.dev/install.sh | sh
    
ENV PASSWORD=sagar1811

EXPOSE 8443

CMD ["code-server", "--bind-addr", "0.0.0.0:8443"]
